### PR TITLE
Add argument support to mcv.upstart

### PR DESCRIPTION
**Pull request by andrewberls**
Ex:

```python
mcv.upstart.start(
    'my-service',
    restart=True,
    args=['HOSTNAME=', 'my-hostname'])
```

```
# my-service.conf
exec echo $HOSTNAME
```

Trello:
Verification:

### CODE REVIEW

**Comment by elliot42** [comment]
I wasn't aware of upstart arguments being a thing?  For example, how can it have arguments when automatically starting services at startup?  It also means starting a service is more complex because it can't self-start with default args

**Comment by andrewberls** [comment]
It's possible! This was largely based on http://askubuntu.com/questions/518048/upstart-multiple-parameters

This is motivated by remote_syslog living within upstart; we want to set a dynamic hostname with a pattern to define groups within papertrail (ex: `service-01`, `service-02`, globbed by `service-*`) and this enables properly configuring that

**Comment by elliot42** [comment]
I don't think this is the best approach.  From what I can tell, this looks like the way it works is that Upstart is reading environment variables, and the suggested approach is to override environment variables before running upstart.  We already have a fully generalized way to override environment variables:

```python
with mcv.env.context({'FOO': 'bar'}):
  do_whatever_you_want_in_here_like_eg_echo_foo
```

Inside that context, the environment variable `FOO` will be bound to the value `'bar'`.  (And it'll be nicely cleaned up outside that context).

This mechanism should give you the behavior you want while being fully orthogonal and composable with anything else, and not specific to Upstart.

**Comment by andrewberls** [comment]
Interesting point; I'll give that a shot, would be nice to not need any of this

**Pull request closed without merging**
